services:
  - type: web
    name: roundsiq
    env: python
    rootDir: api
    plan: free
    autoDeploy: true
    buildCommand: >
      python -m pip install -U pip setuptools wheel &&
      PIP_PREFER_BINARY=1 pip install --only-binary=:all: "numpy==1.26.4" "Pillow==10.3.0" &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: SECRET_KEY
        sync: false
      - key: MAX_ANALYZE_IMAGES
        value: "8"
