services:
  - type: web
    name: medical-ai
    env: python
    rootDir: api
    plan: free
    autoDeploy: true
    buildCommand: "python -m pip install -U pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app"
    envVars:
       - key: PYTHON_VERSION
         value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        value: "3306"          # set here or via dashboard
      - key: SECRET_KEY
        sync: false            # add in dashboard
      - key: MAX_ANALYZE_IMAGES
        value: "8"
